# -*- coding: utf-8 -*-
"""flatten1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TIL8Q_IkVLmFLXZ8-8LIB4q6YN-5ZUX1
"""

import tensorflow as tf
import pandas as pd

"""With reshape"""

(독립, 종속), _ = tf.keras.datasets.mnist.load_data()
print(독립.shape, 종속.shape)

독립 = 독립.reshape(60000, 784)
종속 = pd.get_dummies(종속) #원핫인코딩
print(독립.shape, 종속.shape)

X = tf.keras.layers.Input(shape=[784])
H = tf.keras.layers.Dense(84, activation='swish')(X)
Y = tf.keras.layers.Dense(10, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

model.fit(독립, 종속, epochs=10)

pred = model.predict(독립[0:5])
pd.DataFrame(pred).round(2) #round==반올림

종속[0:5]

"""With flatten"""

#데이터 준비

(독립, 종속), _ = tf.keras.datasets.mnist.load_data()
print(독립.shape, 종속.shape)

# 독립 = 독립.reshape(60000, 784)
종속 = pd.get_dummies(종속) #원핫인코딩
print(독립.shape, 종속.shape)

X = tf.keras.layers.Input(shape=[28,28])
H = tf.keras.layers.Flatten()(X)
H = tf.keras.layers.Dense(84, activation='swish')(H)
Y = tf.keras.layers.Dense(10, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

model.fit(독립, 종속, epochs=5)